INSERT INTO "ROOT"."ATTACHED_TAGS" (T_NAME) VALUES ('politic');
INSERT INTO "ROOT"."ATTACHED_TAGS" (T_NAME) VALUES ('belarus');
INSERT INTO "ROOT"."ATTACHED_TAGS" (T_NAME) VALUES ('it');
INSERT INTO "ROOT"."ATTACHED_TAGS" (T_NAME) VALUES ('russia');
INSERT INTO "ROOT"."ATTACHED_TAGS" (T_NAME) VALUES ('usa');
INSERT INTO "ROOT"."ATTACHED_TAGS" (T_NAME) VALUES ('mens');
INSERT INTO "ROOT"."ATTACHED_TAGS" (T_NAME) VALUES ('womens');
INSERT INTO "ROOT"."ATTACHED_TAGS" (T_NAME) VALUES ('child');
INSERT INTO "ROOT"."ATTACHED_TAGS" (T_NAME) VALUES ('school');
INSERT INTO "ROOT"."ATTACHED_TAGS" (T_NAME) VALUES ('university');
INSERT INTO "ROOT"."ATTACHED_TAGS" (T_NAME) VALUES ('cars');
INSERT INTO "ROOT"."ATTACHED_TAGS" (T_NAME) VALUES ('moto');
INSERT INTO "ROOT"."ATTACHED_TAGS" (T_NAME) VALUES ('trucks');
INSERT INTO "ROOT"."ATTACHED_TAGS" (T_NAME) VALUES ('nature');
INSERT INTO "ROOT"."ATTACHED_TAGS" (T_NAME) VALUES ('stars');
INSERT INTO "ROOT"."ATTACHED_TAGS" (T_NAME) VALUES ('sport');
INSERT INTO "ROOT"."ATTACHED_TAGS" (T_NAME) VALUES ('chicago');
INSERT INTO "ROOT"."ATTACHED_TAGS" (T_NAME) VALUES ('culture');
INSERT INTO "ROOT"."ATTACHED_TAGS" (T_NAME) VALUES ('music');


INSERT INTO "ROOT"."AUTHORS" (A_NAME, A_SURNAME) VALUES ('Ben', 'Black');
INSERT INTO "ROOT"."AUTHORS" (A_NAME, A_SURNAME) VALUES ('John', 'Black');
INSERT INTO "ROOT"."AUTHORS" (A_NAME, A_SURNAME) VALUES ('John', 'Snow');
INSERT INTO "ROOT"."AUTHORS" (A_NAME, A_SURNAME) VALUES ('Ned', 'Stark');
INSERT INTO "ROOT"."AUTHORS" (A_NAME, A_SURNAME) VALUES ('Rob', 'Stark');
INSERT INTO "ROOT"."AUTHORS" (A_NAME, A_SURNAME) VALUES ('Sansa', 'Stark');
INSERT INTO "ROOT"."AUTHORS" (A_NAME, A_SURNAME) VALUES ('Tirion', 'Lanister');
INSERT INTO "ROOT"."AUTHORS" (A_NAME, A_SURNAME) VALUES ('Kate', 'Stark');
INSERT INTO "ROOT"."AUTHORS" (A_NAME, A_SURNAME) VALUES ('Ruse', 'Bolton');
INSERT INTO "ROOT"."AUTHORS" (A_NAME, A_SURNAME) VALUES ('Greg', 'Cligan');
INSERT INTO "ROOT"."AUTHORS" (A_NAME, A_SURNAME) VALUES ('Marg', 'Lanister');
INSERT INTO "ROOT"."AUTHORS" (A_NAME, A_SURNAME) VALUES ('Erlich', 'Bachman');
INSERT INTO "ROOT"."AUTHORS" (A_NAME, A_SURNAME) VALUES ('Bet', 'Man');
INSERT INTO "ROOT"."AUTHORS" (A_NAME, A_SURNAME) VALUES ('Super', 'Mario');
INSERT INTO "ROOT"."AUTHORS" (A_NAME, A_SURNAME) VALUES ('Eliz', 'Brown');
INSERT INTO "ROOT"."AUTHORS" (A_NAME, A_SURNAME) VALUES ('Bart', 'Simpson');
INSERT INTO "ROOT"."AUTHORS" (A_NAME, A_SURNAME) VALUES ('Gomer', 'Simpson');
INSERT INTO "ROOT"."AUTHORS" (A_NAME, A_SURNAME) VALUES ('Liz', 'Simpson');
INSERT INTO "ROOT"."AUTHORS" (A_NAME, A_SURNAME) VALUES ('Patric', 'Star');
INSERT INTO "ROOT"."AUTHORS" (A_NAME, A_SURNAME) VALUES ('Logvinov', 'Ivan');


INSERT INTO "ROOT"."NEWS" (N_MAIN_TITLE, N_SHORT_TITLE, N_DATE_PUBLISHING, N_MAIN_PHOTO, N_CONTENT) VALUES ('Belarus', 'win', TO_DATE('2016-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'belaurs.png', 'Belaurs won Europe games');
INSERT INTO "ROOT"."NEWS" (N_MAIN_TITLE, N_SHORT_TITLE, N_DATE_PUBLISHING, N_MAIN_PHOTO, N_CONTENT) VALUES ('Russia', 'win', TO_DATE('2016-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'russia.png', 'Russia won Olymp games');
INSERT INTO "ROOT"."NEWS" (N_MAIN_TITLE, N_SHORT_TITLE, N_DATE_PUBLISHING, N_MAIN_PHOTO, N_CONTENT) VALUES ('VW', 'win', TO_DATE('2016-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'vw.png', 'VW create good cars');
INSERT INTO "ROOT"."NEWS" (N_MAIN_TITLE, N_SHORT_TITLE, N_DATE_PUBLISHING, N_MAIN_PHOTO, N_CONTENT) VALUES ('Toyota', 'win', TO_DATE('2016-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'belaurs.png', 'toyota create good cars');
INSERT INTO "ROOT"."NEWS" (N_MAIN_TITLE, N_SHORT_TITLE, N_DATE_PUBLISHING, N_MAIN_PHOTO, N_CONTENT) VALUES ('peageout', 'bad', TO_DATE('2016-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'car.png', 'peageout create bad cars');
INSERT INTO "ROOT"."NEWS" (N_MAIN_TITLE, N_SHORT_TITLE, N_DATE_PUBLISHING, N_MAIN_PHOTO, N_CONTENT) VALUES ('gealy', 'super', TO_DATE('2016-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'belaurs.png', 'gealy create bad cars');
INSERT INTO "ROOT"."NEWS" (N_MAIN_TITLE, N_SHORT_TITLE, N_DATE_PUBLISHING, N_MAIN_PHOTO, N_CONTENT) VALUES ('Chealsea', 'win', TO_DATE('2012-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'champions.png', 'Chealsea won league');
INSERT INTO "ROOT"."NEWS" (N_MAIN_TITLE, N_SHORT_TITLE, N_DATE_PUBLISHING, N_MAIN_PHOTO, N_CONTENT) VALUES ('Baern', 'win', TO_DATE('2013-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'baerns.png', 'Baern won league');
INSERT INTO "ROOT"."NEWS" (N_MAIN_TITLE, N_SHORT_TITLE, N_DATE_PUBLISHING, N_MAIN_PHOTO, N_CONTENT) VALUES ('Real', 'win', TO_DATE('2014-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'real.png', 'ral won league');
INSERT INTO "ROOT"."NEWS" (N_MAIN_TITLE, N_SHORT_TITLE, N_DATE_PUBLISHING, N_MAIN_PHOTO, N_CONTENT) VALUES ('Barcelona', 'win', TO_DATE('2015-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'barcelona.png', 'barcelona won league');
INSERT INTO "ROOT"."NEWS" (N_MAIN_TITLE, N_SHORT_TITLE, N_DATE_PUBLISHING, N_MAIN_PHOTO, N_CONTENT) VALUES ('Real', 'win', TO_DATE('2016-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'belaurs.png', 'Real won Europe games');
INSERT INTO "ROOT"."NEWS" (N_MAIN_TITLE, N_SHORT_TITLE, N_DATE_PUBLISHING, N_MAIN_PHOTO, N_CONTENT) VALUES ('Chicago', 'win', TO_DATE('2010-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'default.png', 'Winners of nhl');
INSERT INTO "ROOT"."NEWS" (N_MAIN_TITLE, N_SHORT_TITLE, N_DATE_PUBLISHING, N_MAIN_PHOTO, N_CONTENT) VALUES ('St louis', 'win', TO_DATE('2011-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'default.png', 'Winners of nhl');
INSERT INTO "ROOT"."NEWS" (N_MAIN_TITLE, N_SHORT_TITLE, N_DATE_PUBLISHING, N_MAIN_PHOTO, N_CONTENT) VALUES ('Detroit', 'win', TO_DATE('2012-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'default.png', 'Winners of nhl');
INSERT INTO "ROOT"."NEWS" (N_MAIN_TITLE, N_SHORT_TITLE, N_DATE_PUBLISHING, N_MAIN_PHOTO, N_CONTENT) VALUES ('Calgary', 'win', TO_DATE('2013-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'default.png', 'Calgary won Europe games');
INSERT INTO "ROOT"."NEWS" (N_MAIN_TITLE, N_SHORT_TITLE, N_DATE_PUBLISHING, N_MAIN_PHOTO, N_CONTENT) VALUES ('Ukraine', 'win', TO_DATE('2013-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'default.png', 'ukraine won Europe games');
INSERT INTO "ROOT"."NEWS" (N_MAIN_TITLE, N_SHORT_TITLE, N_DATE_PUBLISHING, N_MAIN_PHOTO, N_CONTENT) VALUES ('Island', 'win', TO_DATE('2011-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'default.png', 'Island won Europe games');
INSERT INTO "ROOT"."NEWS" (N_MAIN_TITLE, N_SHORT_TITLE, N_DATE_PUBLISHING, N_MAIN_PHOTO, N_CONTENT) VALUES ('Gb', 'win', TO_DATE('2016-11-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'default.png', 'Gb won Europe games');
INSERT INTO "ROOT"."NEWS" (N_MAIN_TITLE, N_SHORT_TITLE, N_DATE_PUBLISHING, N_MAIN_PHOTO, N_CONTENT) VALUES ('usa', 'win', TO_DATE('2016-12-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'default.png', 'Belaurs won Europe games');
INSERT INTO "ROOT"."NEWS" (N_MAIN_TITLE, N_SHORT_TITLE, N_DATE_PUBLISHING, N_MAIN_PHOTO, N_CONTENT) VALUES ('brazil', 'win', TO_DATE('2016-10-18 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'default.png', 'Belaurs won Europe games');

INSERT INTO "ROOT"."ROLE" (R_NAME) VALUES ('MODERATOR');
INSERT INTO "ROOT"."ROLE" (R_NAME) VALUES ('USER');
INSERT INTO "ROOT"."ROLE" (R_NAME) VALUES ('ADMIN');



INSERT INTO "ROOT"."USERS" (U_LOGIN, U_PASSWORD, U_ROLE) VALUES ('fx943', 'asdadeawewwe', '1');
INSERT INTO "ROOT"."USERS" (U_LOGIN, U_PASSWORD, U_ROLE) VALUES ('sa345', 'dsdsdsdsds', '1');
INSERT INTO "ROOT"."USERS" (U_LOGIN, U_PASSWORD, U_ROLE) VALUES ('afafs4', 'asdadasd', '1');
INSERT INTO "ROOT"."USERS" (U_LOGIN, U_PASSWORD, U_ROLE) VALUES ('sdsds4', 'vfvbtbtbtbtb', '1');
INSERT INTO "ROOT"."USERS" (U_LOGIN, U_PASSWORD, U_ROLE) VALUES ('vbvertqwe', 'vgbfgbfgbfgbfgb', '1');
INSERT INTO "ROOT"."USERS" (U_LOGIN, U_PASSWORD, U_ROLE) VALUES ('cxvdfbdbe', '2sfsefsdfsdfsdf', '1');
INSERT INTO "ROOT"."USERS" (U_LOGIN, U_PASSWORD, U_ROLE) VALUES ('asdasfeefve34', 'vrgrverververs', '1');
INSERT INTO "ROOT"."USERS" (U_LOGIN, U_PASSWORD, U_ROLE) VALUES ('wefwefwge3422', 'sdfsdfsdfsdfsdf', '1');
INSERT INTO "ROOT"."USERS" (U_LOGIN, U_PASSWORD, U_ROLE) VALUES ('qweqweqwe', '23degrergsgrg', '1');
INSERT INTO "ROOT"."USERS" (U_LOGIN, U_PASSWORD, U_ROLE) VALUES ('sdfsfsfssddfsdfs', '34234', '1');
INSERT INTO "ROOT"."USERS" (U_LOGIN, U_PASSWORD, U_ROLE) VALUES ('fdsdfsf', '3dfdsfsf', '1');
INSERT INTO "ROOT"."USERS" (U_LOGIN, U_PASSWORD, U_ROLE) VALUES ('dsfdfsef', 'efewsdfwfes', '1');
INSERT INTO "ROOT"."USERS" (U_LOGIN, U_PASSWORD, U_ROLE) VALUES ('dfsfetgsgsg', 'zcvxcvxcvfd', '1');
INSERT INTO "ROOT"."USERS" (U_LOGIN, U_PASSWORD, U_ROLE) VALUES ('xccvfdfvt', 'qdasffsefwefdsfds', '1');
INSERT INTO "ROOT"."USERS" (U_LOGIN, U_PASSWORD, U_ROLE) VALUES ('sdcvxcvxvxcvxc', 'efsdfzcvxvvxcvsvcx', '1');
INSERT INTO "ROOT"."USERS" (U_LOGIN, U_PASSWORD, U_ROLE) VALUES ('afadzcsdvs', 'sdvsvxcvdx', '4');
INSERT INTO "ROOT"."USERS" (U_LOGIN, U_PASSWORD, U_ROLE) VALUES ('dfsfetgsgwwsg', 'zcvxcvxcvfd', '1');
INSERT INTO "ROOT"."USERS" (U_LOGIN, U_PASSWORD, U_ROLE) VALUES ('xccvfdfv11t', 'qdasffsefwefdsfds', '1');
INSERT INTO "ROOT"."USERS" (U_LOGIN, U_PASSWORD, U_ROLE) VALUES ('sdcvxcvxvxcwwwvxc', 'efsdfzcvxvvxcvsvcx', '3');
INSERT INTO "ROOT"."USERS" (U_LOGIN, U_PASSWORD, U_ROLE) VALUES ('afadzcswwwdvs', 'sdvsvxcvdx', '2');


INSERT INTO "ROOT"."COMMENT_NEWS" (USER_ID_USER, C_DATE, C_CONTENT, C_NEWS) VALUES ('1', TO_DATE('2016-10-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Foo', '5';
INSERT INTO "ROOT"."COMMENT_NEWS" (USER_ID_USER, C_DATE, C_CONTENT, C_NEWS) VALUES ('1', TO_DATE('2016-10-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Foo', '5';
INSERT INTO "ROOT"."COMMENT_NEWS" (USER_ID_USER, C_DATE, C_CONTENT, C_NEWS) VALUES ('1', TO_DATE('2016-10-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Foo', '5';
INSERT INTO "ROOT"."COMMENT_NEWS" (USER_ID_USER, C_DATE, C_CONTENT, C_NEWS) VALUES ('1', TO_DATE('2016-10-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Foo', '5';
INSERT INTO "ROOT"."COMMENT_NEWS" (USER_ID_USER, C_DATE, C_CONTENT, C_NEWS) VALUES ('1', TO_DATE('2016-10-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Foo', '5';
INSERT INTO "ROOT"."COMMENT_NEWS" (USER_ID_USER, C_DATE, C_CONTENT, C_NEWS) VALUES ('1', TO_DATE('2016-10-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Foo', '5';
INSERT INTO "ROOT"."COMMENT_NEWS" (USER_ID_USER, C_DATE, C_CONTENT, C_NEWS) VALUES ('1', TO_DATE('2016-10-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Foo', '5';
INSERT INTO "ROOT"."COMMENT_NEWS" (USER_ID_USER, C_DATE, C_CONTENT, C_NEWS) VALUES ('1', TO_DATE('2016-10-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Foo', '5';
INSERT INTO "ROOT"."COMMENT_NEWS" (USER_ID_USER, C_DATE, C_CONTENT, C_NEWS) VALUES ('1', TO_DATE('2016-10-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Foo', '5';
INSERT INTO "ROOT"."COMMENT_NEWS" (USER_ID_USER, C_DATE, C_CONTENT, C_NEWS) VALUES ('1', TO_DATE('2016-10-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Foo', '5';
INSERT INTO "ROOT"."COMMENT_NEWS" (USER_ID_USER, C_DATE, C_CONTENT, C_NEWS) VALUES ('12', TO_DATE('2016-10-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Foo', '4';
INSERT INTO "ROOT"."COMMENT_NEWS" (USER_ID_USER, C_DATE, C_CONTENT, C_NEWS) VALUES ('8', TO_DATE('2016-10-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Foo', '2';
INSERT INTO "ROOT"."COMMENT_NEWS" (USER_ID_USER, C_DATE, C_CONTENT, C_NEWS) VALUES ('7', TO_DATE('2016-10-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Foo', '17';
INSERT INTO "ROOT"."COMMENT_NEWS" (USER_ID_USER, C_DATE, C_CONTENT, C_NEWS) VALUES ('3', TO_DATE('2016-10-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Foo', '16';
INSERT INTO "ROOT"."COMMENT_NEWS" (USER_ID_USER, C_DATE, C_CONTENT, C_NEWS) VALUES ('4', TO_DATE('2016-10-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Foo', '3';
INSERT INTO "ROOT"."COMMENT_NEWS" (USER_ID_USER, C_DATE, C_CONTENT, C_NEWS) VALUES ('10', TO_DATE('2016-10-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Foo', '15';
INSERT INTO "ROOT"."COMMENT_NEWS" (USER_ID_USER, C_DATE, C_CONTENT, C_NEWS) VALUES ('10', TO_DATE('2016-10-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Good', '15';
INSERT INTO "ROOT"."COMMENT_NEWS" (USER_ID_USER, C_DATE, C_CONTENT, C_NEWS) VALUES ('13', TO_DATE('2016-10-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Foo', '15';
INSERT INTO "ROOT"."COMMENT_NEWS" (USER_ID_USER, C_DATE, C_CONTENT, C_NEWS) VALUES ('13', TO_DATE('2016-11-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Foo', '10';
INSERT INTO "ROOT"."COMMENT_NEWS" (USER_ID_USER, C_DATE, C_CONTENT, C_NEWS) VALUES ('16', TO_DATE('2016-11-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Foo', '10';
INSERT INTO "ROOT"."COMMENT_NEWS" (USER_ID_USER, C_DATE, C_CONTENT, C_NEWS) VALUES ('15', TO_DATE('2014-10-17 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Good', '12';



INSERT INTO "ROOT"."NEWS_HAS_AUTHORS" (AUTHORS_ID, NEWS_ID) VALUES ('1', '1');
INSERT INTO "ROOT"."NEWS_HAS_AUTHORS" (AUTHORS_ID, NEWS_ID) VALUES ('1', '4');
INSERT INTO "ROOT"."NEWS_HAS_AUTHORS" (AUTHORS_ID, NEWS_ID) VALUES ('2', '12');
INSERT INTO "ROOT"."NEWS_HAS_AUTHORS" (AUTHORS_ID, NEWS_ID) VALUES ('2', '20');
INSERT INTO "ROOT"."NEWS_HAS_AUTHORS" (AUTHORS_ID, NEWS_ID) VALUES ('19', '19');
INSERT INTO "ROOT"."NEWS_HAS_AUTHORS" (AUTHORS_ID, NEWS_ID) VALUES ('18', '18');
INSERT INTO "ROOT"."NEWS_HAS_AUTHORS" (AUTHORS_ID, NEWS_ID) VALUES ('17', '17');
INSERT INTO "ROOT"."NEWS_HAS_AUTHORS" (AUTHORS_ID, NEWS_ID) VALUES ('3', '17');
INSERT INTO "ROOT"."NEWS_HAS_AUTHORS" (AUTHORS_ID, NEWS_ID) VALUES ('9', '9');
INSERT INTO "ROOT"."NEWS_HAS_AUTHORS" (AUTHORS_ID, NEWS_ID) VALUES ('4', '9');
INSERT INTO "ROOT"."NEWS_HAS_AUTHORS" (AUTHORS_ID, NEWS_ID) VALUES ('5', '5');
INSERT INTO "ROOT"."NEWS_HAS_AUTHORS" (AUTHORS_ID, NEWS_ID) VALUES ('6', '6');
INSERT INTO "ROOT"."NEWS_HAS_AUTHORS" (AUTHORS_ID, NEWS_ID) VALUES ('8', '8');
INSERT INTO "ROOT"."NEWS_HAS_AUTHORS" (AUTHORS_ID, NEWS_ID) VALUES ('7', '8');
INSERT INTO "ROOT"."NEWS_HAS_AUTHORS" (AUTHORS_ID, NEWS_ID) VALUES ('7', '20');
INSERT INTO "ROOT"."NEWS_HAS_AUTHORS" (AUTHORS_ID, NEWS_ID) VALUES ('5', '12');
INSERT INTO "ROOT"."NEWS_HAS_AUTHORS" (AUTHORS_ID, NEWS_ID) VALUES ('5', '13');
INSERT INTO "ROOT"."NEWS_HAS_AUTHORS" (AUTHORS_ID, NEWS_ID) VALUES ('1', '12');
INSERT INTO "ROOT"."NEWS_HAS_AUTHORS" (AUTHORS_ID, NEWS_ID) VALUES ('4', '11');
INSERT INTO "ROOT"."NEWS_HAS_AUTHORS" (AUTHORS_ID, NEWS_ID) VALUES ('3', '11');
INSERT INTO "ROOT"."NEWS_HAS_AUTHORS" (AUTHORS_ID, NEWS_ID) VALUES ('2', '11');


INSERT INTO "ROOT"."NEWS_HAS_TAGS" (NEWS_ID, ATTACHED_TAGS_ID) VALUES ('1', '1');
INSERT INTO "ROOT"."NEWS_HAS_TAGS" (NEWS_ID, ATTACHED_TAGS_ID) VALUES ('1', '2');
INSERT INTO "ROOT"."NEWS_HAS_TAGS" (NEWS_ID, ATTACHED_TAGS_ID) VALUES ('1', '3');
INSERT INTO "ROOT"."NEWS_HAS_TAGS" (NEWS_ID, ATTACHED_TAGS_ID) VALUES ('2', '5');
INSERT INTO "ROOT"."NEWS_HAS_TAGS" (NEWS_ID, ATTACHED_TAGS_ID) VALUES ('2', '6');
INSERT INTO "ROOT"."NEWS_HAS_TAGS" (NEWS_ID, ATTACHED_TAGS_ID) VALUES ('2', '7');
INSERT INTO "ROOT"."NEWS_HAS_TAGS" (NEWS_ID, ATTACHED_TAGS_ID) VALUES ('2', '8');
INSERT INTO "ROOT"."NEWS_HAS_TAGS" (NEWS_ID, ATTACHED_TAGS_ID) VALUES ('3', '3');
INSERT INTO "ROOT"."NEWS_HAS_TAGS" (NEWS_ID, ATTACHED_TAGS_ID) VALUES ('4', '4');
INSERT INTO "ROOT"."NEWS_HAS_TAGS" (NEWS_ID, ATTACHED_TAGS_ID) VALUES ('5', '5');
INSERT INTO "ROOT"."NEWS_HAS_TAGS" (NEWS_ID, ATTACHED_TAGS_ID) VALUES ('6', '6');
INSERT INTO "ROOT"."NEWS_HAS_TAGS" (NEWS_ID, ATTACHED_TAGS_ID) VALUES ('7', '7');
INSERT INTO "ROOT"."NEWS_HAS_TAGS" (NEWS_ID, ATTACHED_TAGS_ID) VALUES ('8', '8');
INSERT INTO "ROOT"."NEWS_HAS_TAGS" (NEWS_ID, ATTACHED_TAGS_ID) VALUES ('9', '9');
INSERT INTO "ROOT"."NEWS_HAS_TAGS" (NEWS_ID, ATTACHED_TAGS_ID) VALUES ('10', '10');
INSERT INTO "ROOT"."NEWS_HAS_TAGS" (NEWS_ID, ATTACHED_TAGS_ID) VALUES ('11', '11');
INSERT INTO "ROOT"."NEWS_HAS_TAGS" (NEWS_ID, ATTACHED_TAGS_ID) VALUES ('12', '12');
INSERT INTO "ROOT"."NEWS_HAS_TAGS" (NEWS_ID, ATTACHED_TAGS_ID) VALUES ('13', '13');
INSERT INTO "ROOT"."NEWS_HAS_TAGS" (NEWS_ID, ATTACHED_TAGS_ID) VALUES ('14', '14');
INSERT INTO "ROOT"."NEWS_HAS_TAGS" (NEWS_ID, ATTACHED_TAGS_ID) VALUES ('15', '15');





